on:
    push:
        branches:
            - main

name: 🚀 Deploy the website on push

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v2
              with:
                  node-version: '20.13.1'

            - name: 🔨 Build Project
              run: |
                  npm config set legacy-peer-deps true
                  npm install 
                  CI=false npm run build

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ftp.koralbyte.com
                  username: cocoa-app@cocoa-app.com
                  password: ${{ secrets.PROD_FTP_PASSWORD }}
                  protocol: ftps
                  port: 21
                  local-dir: ./dist/
